name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudorpg.PseudoRPG
version: ${revision}
description: RPG Plugin
api-version: 1.13
depend: [PseudoAPI]
softdepend: [Vault]
commands:
  pseudorpg:
    description: PseudoRPG Menu
    aliases: [rpg]
  rpgxp:
    description: Displays XP Stats
    permission: pseudoplayers.xp
  rpgxpskill:
    description: Displays Skill XP Stats
    permission: pseudoplayers.xp
  skillxp:
    description: Modifies skill xp
    permission: pseudoplayers.skillxp
permissions:
  pseudorpg.xp:
    description: Allows the player to view xp stats
    default: true
  pseudorpg.xp.others:
    description: Allows the player to view xp stats for other players
    default: op
    children:
      pseudorpg.xp: true
  pseudorpg.skillxp:
    description: Allows the player to modify skill xp
    default: op
  pseudorpg.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudorpg.reset:
    description: Allows the player to reset the plugin
    default: op
    children:
      pseudorpg.reload: true
  pseudorpg.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudorpg.resetlocalization:
    description: Allows the player to reset the localization
    default: op
    children:
      pseudorpg.reloadlocalization: true
  pseudorpg.*:
    description: Gives the user all PseudoRPG permissions
    default: op
    children:
      pseudorpg.reset: true
      pseudorpg.resetlocalization: true
      pseudorpg.xp.others: true
      pseudorpg.skillxp: true