name: PseudoRPG
author: PseudoResonance
main: io.github.pseudoresonance.pseudorpg.PseudoRPG
version: 0.3.1
description: RPG Plugin
depend: [PseudoAPI]
commands:
  pseudorpg:
    description: PseudoRPG Menu
    aliases: [rpg]
  rpgxp:
    description: Displays XP Stats
  xpskill:
    description: Displays Skill XP Stats
  givexp:
    description: Gives XP
  takexp:
    description: Takes XP
  setxp:
    description: Sets XP
permissions:
  rpg.xp:
    description: Allows the player to view xp stats
    default: true
    children:
      rpg.xp.skill.*: true
  rpg.xp.other:
    description: Allows the player to view xp stats for other players
    default: op
    children:
      rpg.xp: true
      rpg.xp.other.*: true
  rpg.givexp:
    description: Allows the player to give xp
    default: op
  rpg.takexp:
    description: Allows the player to take xp
    default: op
  rpg.setxp:
    description: Allows the player to set xp
    default: op
  rpg.reload:
    description: Allows the player to reload the plugin
    default: op
  rpg.reset:
    description: Allows the player to reset the plugin
    default: op
  rpg.*:
    description: Gives the user all RPG permissions
    default: op
    children:
      rpg.reload: true
      rpg.reset: true
      rpg.xp: true
      rpg.xp.other: true
      rpg.givexp: true
      rpg.takexp: true
      rpg.setxp: true