name: RPG
author: Newoace, WolfLeader116
main: tk.spongenetwork.RPG.RPG
version: 0.1.3
description: SpongeNetwork RPG Plugin
depend:[WolfAPI]
commands:
  rpg:
    description: RPG Menu
permissions:
  rpg.reload:
    description: Allows the player to reload the plugin
    default: op
  rpg.reset:
    description: Allows the player to reset the plugin
    default: op
  rpg.*:
    description: Gives the user all WolfAPI permissions
    default: op
    children:
      rpg.reload: true
      rpg.reset: true